run:
  issues-exit-code: 0

linters:
  disable-all: true
  enable:
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - misspell
    - unparam
    - gofmt
    - goimports
    - deadcode
    - nestif
    - govet
    - golint
    - prealloc
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - rowserrcheck
    - scopelint
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - varcheck
    - exhaustive
    - exportloopref
    - goerr113
    - gofumpt
    - unused

run:
  tests: false

issues:
  exclude-rules:
    - linters:
      - goerr113
      text: "err113: do not define dynamic errors"

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/nakabonne/pbgopy
  golint:
    min-confidence: 0.3
  maligned:
    suggest-new: true
  misspell:
    locale: US
