run:
  issues-exit-code: 0
  tests: false

linters:
  disable-all: true
  enable:
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - misspell
    - unparam
    - gofmt
    - goimports
    - nestif
    - govet
    - prealloc
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - exhaustive
    - exportloopref
    - err113
    - gofumpt
    - unused

issues:
  exclude-rules:
    - linters:
      - err113
      text: "do not define dynamic errors"

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/nakabonne/pbgopy
  misspell:
    locale: US
