before:
  hooks:
    - go mod tidy
builds:
- main: .
  binary: pbgopy
  goos:
    - freebsd
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - ppc64le
    - s390x
    - mips64
    - mips64le
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
  ldflags:
    - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
    - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
    - -s -w

archives:
- replacements:
    386: 32-bit

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - tap:
      owner: nakabonne
      name: homebrew-pbgopy
    homepage: "https://github.com/nakabonne/pbgopy"
    description: "Copy and paste between devices"

nfpms:
  - license: MIT
    maintainer: Ryo Nakao <ryo@nakao.dev>
    homepage: https://github.com/nakabonne/pbgopy
    description: "Copy and paste between devices"
    formats:
      - rpm
      - deb

dockers:
  - dockerfile: Dockerfile
    binaries:
      - pbgopy
    image_templates:
      - "nakabonne/pbgopy:latest"
      - "nakabonne/pbgopy:{{ .Tag }}"
      - "nakabonne/pbgopy:v{{ .Major }}.{{ .Minor }}"
